import 'package:sleep_app/player/music_chooser/items/sound_property.dart';
import 'package:sleep_app/player/music_chooser/music_types_bar/choose_music_bar_model.dart';
import 'package:sleep_app/player/storage/sounds_storage/sound_item.dart';

const Map<String, SoundItem> sounds = {
  "Rain": SoundItem(
    property: SoundProperties.unlocked,
    title: "Rain",
    type: SoundType.nature,
    info: "",
  ),
  "Fire": SoundItem(
    property: SoundProperties.unlocked,
    title: "Fire",
    type: SoundType.nature,
    info: "",
  ),
  "Forest": SoundItem(
    property: SoundProperties.unlocked,
    title: "Forest",
    type: SoundType.nature,
    info: "",
  ),
  "Night": SoundItem(
    property: SoundProperties.unlocked,
    title: "Night",
    type: SoundType.nature,
    info: "",
  ),
  "Ocean": SoundItem(
    property: SoundProperties.unlocked,
    title: "Ocean",
    type: SoundType.nature,
    info: "",
  ),
  "River": SoundItem(
    property: SoundProperties.unlocked,
    title: "River",
    type: SoundType.nature,
    info: "",
  ),
  "Sea": SoundItem(
    property: SoundProperties.unlocked,
    title: "Sea",
    type: SoundType.nature,
    info: "",
  ),
  "Thunder": SoundItem(
    property: SoundProperties.unlocked,
    title: "Thunder",
    type: SoundType.nature,
    info: "",
  ),
  "Snow": SoundItem(
    property: SoundProperties.unlocked,
    title: "Snow",
    type: SoundType.nature,
    info: "",
  ),
  "Waterfall": SoundItem(
    property: SoundProperties.unlocked,
    title: "Waterfall",
    type: SoundType.nature,
    info: "",
  ),
  "Crowd": SoundItem(
    property: SoundProperties.unlocked,
    title: "Crowd",
    type: SoundType.urban,
    info: "",
  ),
  "Kids": SoundItem(
    property: SoundProperties.unlocked,
    title: "Kids",
    type: SoundType.baby,
    info: "",
  ),
  "Subway": SoundItem(
    property: SoundProperties.unlocked,
    title: "Subway",
    type: SoundType.urban,
    info: "",
  ),
  "Train": SoundItem(
    property: SoundProperties.unlocked,
    title: "Train",
    type: SoundType.urban,
    info: "",
  ),
  "Cricket": SoundItem(
    property: SoundProperties.unlocked,
    title: "Cricket",
    type: SoundType.nature,
    info: "",
  ),
  "Live": SoundItem(
    property: SoundProperties.unlocked,
    title: "Live",
    type: SoundType.home,
    info: "",
  ),
  "Phone": SoundItem(
    property: SoundProperties.unlocked,
    title: "Phone",
    type: SoundType.home,
    info: "",
  ),
  "Seagulls": SoundItem(
    property: SoundProperties.unlocked,
    title: "Seagulls",
    type: SoundType.animals,
    info: "",
  ),
  "Cat": SoundItem(
    property: SoundProperties.unlocked,
    title: "Cat",
    type: SoundType.animals,
    info: "",
  ),
  "Cows": SoundItem(
    property: SoundProperties.unlocked,
    title: "Cows",
    type: SoundType.animals,
    info: "",
  ),
  "Dog": SoundItem(
    property: SoundProperties.locked,
    title: "Dog",
    type: SoundType.animals,
    info: "",
  ),
  "Dolphins": SoundItem(
    property: SoundProperties.unlocked,
    title: "Dolphins",
    type: SoundType.animals,
    info: "",
  ),
  "Frogs": SoundItem(
    property: SoundProperties.unlocked,
    title: "Frogs",
    type: SoundType.animals,
    info: "",
  ),
  "Horse": SoundItem(
    property: SoundProperties.unlocked,
    title: "Horse",
    type: SoundType.animals,
    info: "",
  ),
  "Owl": SoundItem(
    property: SoundProperties.unlocked,
    title: "Owl",
    type: SoundType.animals,
    info: "",
  ),
  "Wolf": SoundItem(
    property: SoundProperties.unlocked,
    title: "Wolf",
    type: SoundType.animals,
    info: "",
  ),
  "Whale": SoundItem(
    property: SoundProperties.unlocked,
    title: "Whale",
    type: SoundType.animals,
    info: "",
  ),
  "Microwave": SoundItem(
    property: SoundProperties.unlocked,
    title: "Microwave",
    type: SoundType.home,
    info: "",
  ),
  "Metronome": SoundItem(
    property: SoundProperties.unlocked,
    title: "Metronome",
    type: SoundType.whiteNoise,
    info: "",
  ),
  "Hairdryer": SoundItem(
    property: SoundProperties.unlocked,
    title: "Hairdryer",
    type: SoundType.home,
    info: "",
  ),
  "Fan": SoundItem(
    property: SoundProperties.unlocked,
    title: "Fan",
    type: SoundType.home,
    info: "",
  ),
  "Teapot": SoundItem(
    property: SoundProperties.unlocked,
    title: "Teapot",
    type: SoundType.home,
    info: "",
  ),
  "Vacuum Cleaner": SoundItem(
    property: SoundProperties.unlocked,
    title: "Vacuum Cleaner",
    type: SoundType.home,
    info: "",
  ),
  "Washing Machine": SoundItem(
    property: SoundProperties.unlocked,
    title: "Washing Machine",
    type: SoundType.home,
    info: "",
  ),
  "Watch": SoundItem(
    property: SoundProperties.unlocked,
    title: "Watch",
    type: SoundType.whiteNoise,
    info: "",
  ),
  "Lullaby": SoundItem(
    property: SoundProperties.unlocked,
    title: "Lullaby",
    type: SoundType.whiteNoise,
    info: "",
  ),
  "Music Box": SoundItem(
    property: SoundProperties.unlocked,
    title: "Music Box",
    type: SoundType.whiteNoise,
    info: "",
  ),
  "Refrigerator": SoundItem(
    property: SoundProperties.unlocked,
    title: "Refrigerator",
    type: SoundType.whiteNoise,
    info: "",
  ),
  "Whisper": SoundItem(
    property: SoundProperties.unlocked,
    title: "Whisper",
    type: SoundType.whiteNoise,
    info: "",
  ),
};
