import 'package:sleep_app/fiveth_frame/music_chooser/items/sound_item.dart';
import 'package:sleep_app/fiveth_frame/music_chooser/items/sound_property.dart';
import 'package:sleep_app/fiveth_frame/music_types_bar/choose_music_bar_model.dart';

const Map<String, SoundItem> sounds = {
  "Rain": SoundItem(
      property: SoundProperties.unlocked,
      title: "Rain",
      type: SoundType.nature),
  "Fire": SoundItem(
      property: SoundProperties.unlocked,
      title: "Fire",
      type: SoundType.nature),
  "Forest": SoundItem(
      property: SoundProperties.unlocked,
      title: "Forest",
      type: SoundType.nature),
  "Night": SoundItem(
      property: SoundProperties.unlocked,
      title: "Night",
      type: SoundType.nature),
  "Ocean": SoundItem(
      property: SoundProperties.unlocked,
      title: "Ocean",
      type: SoundType.nature),
  "River": SoundItem(
      property: SoundProperties.unlocked,
      title: "River",
      type: SoundType.nature),
  "Sea": SoundItem(
      property: SoundProperties.unlocked, title: "Sea", type: SoundType.nature),
  "Thunder": SoundItem(
      property: SoundProperties.unlocked,
      title: "Thunder",
      type: SoundType.nature),
  "Snow": SoundItem(
      property: SoundProperties.unlocked,
      title: "Snow",
      type: SoundType.nature),
  "Waterfall": SoundItem(
      property: SoundProperties.unlocked,
      title: "Waterfall",
      type: SoundType.nature),
  "Crowd": SoundItem(
      property: SoundProperties.unlocked,
      title: "Crowd",
      type: SoundType.urban),
  "Kids": SoundItem(
      property: SoundProperties.unlocked, title: "Kids", type: SoundType.baby),
  "Subway": SoundItem(
      property: SoundProperties.unlocked,
      title: "Subway",
      type: SoundType.urban),
  "Train": SoundItem(
      property: SoundProperties.unlocked,
      title: "Train",
      type: SoundType.urban),
  "Cricket": SoundItem(
      property: SoundProperties.unlocked,
      title: "Cricket",
      type: SoundType.nature),
  "Live": SoundItem(
      property: SoundProperties.unlocked, title: "Live", type: SoundType.home),
  "Phone": SoundItem(
      property: SoundProperties.unlocked, title: "Phone", type: SoundType.home),
  "Seagulls": SoundItem(
      property: SoundProperties.unlocked,
      title: "Seagulls",
      type: SoundType.animals),
  "Cat": SoundItem(
      property: SoundProperties.unlocked,
      title: "Cat",
      type: SoundType.animals),
  "Cows": SoundItem(
      property: SoundProperties.unlocked,
      title: "Cows",
      type: SoundType.animals),
  "Dog": SoundItem(
      property: SoundProperties.unlocked,
      title: "Dog",
      type: SoundType.animals),
  "Dolphins": SoundItem(
      property: SoundProperties.unlocked,
      title: "Dolphins",
      type: SoundType.animals),
  "Frogs": SoundItem(
      property: SoundProperties.unlocked,
      title: "Frogs",
      type: SoundType.animals),
  "Horse": SoundItem(
      property: SoundProperties.unlocked,
      title: "Horse",
      type: SoundType.animals),
  "Owl": SoundItem(
      property: SoundProperties.unlocked,
      title: "Owl",
      type: SoundType.animals),
  "Wolf": SoundItem(
      property: SoundProperties.unlocked,
      title: "Wolf",
      type: SoundType.animals),
  "Whale": SoundItem(
      property: SoundProperties.unlocked,
      title: "Whale",
      type: SoundType.animals),
  "Microwave": SoundItem(
      property: SoundProperties.unlocked,
      title: "Microwave",
      type: SoundType.home),
  "Metronome": SoundItem(
      property: SoundProperties.unlocked,
      title: "Metronome",
      type: SoundType.whiteNoise),
  "Hairdryer": SoundItem(
      property: SoundProperties.unlocked,
      title: "Hairdryer",
      type: SoundType.home),
  "Fan": SoundItem(
      property: SoundProperties.unlocked, title: "Fan", type: SoundType.home),
  "Teapot": SoundItem(
      property: SoundProperties.unlocked,
      title: "Teapot",
      type: SoundType.home),
  "Vacuum Cleaner": SoundItem(
      property: SoundProperties.unlocked,
      title: "Vacuum Cleaner",
      type: SoundType.home),
  "Washing Machine": SoundItem(
      property: SoundProperties.unlocked,
      title: "Washing Machine",
      type: SoundType.home),
  "Watch": SoundItem(
      property: SoundProperties.unlocked,
      title: "Watch",
      type: SoundType.whiteNoise),
  "Lullaby": SoundItem(
      property: SoundProperties.unlocked,
      title: "Lullaby",
      type: SoundType.whiteNoise),
  "Music Box": SoundItem(
      property: SoundProperties.unlocked,
      title: "Music Box",
      type: SoundType.whiteNoise),
  "Refrigerator": SoundItem(
      property: SoundProperties.unlocked,
      title: "Refrigerator",
      type: SoundType.whiteNoise),
  "Whisper": SoundItem(
      property: SoundProperties.unlocked,
      title: "Whisper",
      type: SoundType.whiteNoise),
};
